# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  profiles:
    active: local
  redis:
    database: 0
    host: 192.168.2.9
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

shiro:
  cluster: true  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  session:
    prefix: "yh:session:"
    timeout: 86400
  anon:
    - /login
